FROM alpine/git as download_image
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin https://github.com/halushko/kino-cat.git && \
    git config core.sparseCheckout true && \
    echo "config/commands/transmission/" >> .git/info/sparse-checkout && \
    echo "config/config_files/transmission/" >> .git/info/sparse-checkout && \
    git pull origin master

FROM openjdk:8-alpine as torrent
VOLUME ["/home/jars"]
VOLUME ["/home/app"]
RUN mkdir -p /home/jars
RUN mkdir -p /home/app

VOLUME ["/sys/fs/cgroup"]

RUN apk add openrc

RUN apk add transmission-daemon transmission-cli

COPY --from=download_image /home/git/code/kino-cat/config/config_files/transmission /var/lib/transmission/config
COPY --from=download_image /home/git/code/kino-cat/config/commands/transmission /home/app

RUN chmod +x /var/lib/transmission/config/after_download.sh
RUN openrc
RUN touch /run/openrc/softlevel

CMD chmod 777 -R /home/app && \
    chmod +X /home/app/*.sh && \
    cp /home/jars/kot_utils.jar /home/app && \
    cp /home/jars/torrent.jar /home/app && \
    mkdir -p /home/media/torrent/downloads && \
    mkdir -p /home/media/torrent/complete && \
    mkdir -p /home/media/torrent/torrent_files && \
    chown transmission -R /home/media && \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service transmission-daemon stop && \
    rc-service transmission-daemon start && \
    java -jar /home/app/torrent.jar