FROM openjdk:8-alpine as microBot
VOLUME ["/home/jars"]
VOLUME ["/home/app"]
RUN mkdir -p /home/jars
RUN mkdir -p /home/app
CMD chmod 777 -R /home/app && \
    cp /home/jars/kot_utils.jar /home/app && \
    cp /home/jars/micro_bot.jar /home/app && \
    java -jar /home/app/micro_bot.jar