FROM alpine/git as download_image
ENV VERSION="v 1.1"
RUN ls /home
RUN mkdir -p /home/git/code
RUN cd /home/git/code && git clone https://github.com/halushko/kino-cat.git
RUN ls /home/git/code/kino-cat

FROM gradle:jdk8-alpine as build_image
RUN ls /home
RUN mkdir -p /home/gradle/code/rabKot
RUN mkdir -p /home/gradle/code/microBot
RUN mkdir -p /home/gradle/app

COPY --from=download_image /home/git/code/kino-cat/rabKot /home/gradle/code/rabKot
COPY --from=download_image /home/git/code/kino-cat/microBot /home/gradle/code/microBot

RUN ls /home/gradle/code/rabKot
RUN ls /home/gradle/code/microBot
RUN cd /home/gradle/code/rabKot && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar
RUN cd /home/gradle/code/microBot && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/micro_bot.jar

RUN ls /home/gradle/app

#ENTRYPOINT ["java", "-jar", "/app/micro_bot.jar"]