FROM alpine/git as download_image
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin https://github.com/halushko/kino-cat.git && \
    git config core.sparseCheckout true && \
    echo "rabKot/" >> .git/info/sparse-checkout && \
    echo "minidlna/" >> .git/info/sparse-checkout && \
    echo "config/commands/minidlna/" >> .git/info/sparse-checkout && \
    echo "config/config_files/minidlna/" >> .git/info/sparse-checkout && \
    git pull origin master

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app

COPY --chown=gradle:gradle --from=download_image /home/git/code /home/gradle/code

RUN cd /home/gradle/code/kino-cat/rabKot && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar
RUN cd /home/gradle/code/kino-cat/minidlna && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/minidlna.jar

FROM openjdk:8-alpine
RUN apk add openrc
VOLUME ["/sys/fs/cgroup"]
COPY --from=build_image /home/gradle/app /home/app

RUN apk add minidlna
COPY --from=download_image /home/git/code/kino-cat/config/config_files/minidlna /etc
COPY --from=download_image /home/git/code/kino-cat/config/commands/minidlna /home/app

RUN openrc
RUN touch /run/openrc/softlevel
RUN chmod +X /home/app/*.sh
RUN chmod 777 -R /home/app

CMD mkdir -p /home/media/minidlna/complete && \
    chown minidlna -R /home/media/minidlna/complete && \

    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service minidlna stop && \
    rc-service minidlna start && \
    java -jar /home/app/minidlna.jar