FROM alpine/git as download_image
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin https://github.com/halushko/kino-cat.git && \
    git config core.sparseCheckout true && \
    echo "rabKot/" >> .git/info/sparse-checkout && \
    echo "torrent/" >> .git/info/sparse-checkout && \
    echo "config/commands/transmission/" >> .git/info/sparse-checkout && \
    echo "config/config_files/transmission/" >> .git/info/sparse-checkout && \
    git pull origin master

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app

COPY --chown=gradle:gradle --from=download_image /home/git/code /home/gradle/code

RUN cd /home/gradle/code/kino-cat/rabKot && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar
RUN cd /home/gradle/code/kino-cat/torrent && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/torrent.jar

FROM openjdk:8-alpine
RUN apk add transmission-daemon transmission-cli openrc
VOLUME ["/sys/fs/cgroup"]
COPY --from=build_image /home/gradle/app /home/app
COPY --from=download_image /home/git/code/kino-cat/config/config_files/transmission /var/lib/transmission/config
COPY --from=download_image /home/git/code/kino-cat/config/commands/transmission /home/app

RUN chmod +x /var/lib/transmission/config/after_download.sh
RUN openrc
RUN touch /run/openrc/softlevel
RUN chmod +X /home/app/*.sh
RUN chown transmission -R /home/media
RUN chmod 777 -R /home/app

CMD mkdir -p /home/media/torrent/downloads && \
    mkdir -p /home/media/torrent/complete && \
    mkdir -p /home/media/torrent/torrent_files && \

    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service transmission-daemon start && \
    java -jar /home/app/torrent.jar