FROM openjdk:20-ea-35-jdk-slim
RUN apt-get update && apt-get install -f -y transmission-cli
RUN mkdir -p /tmp/unapproved && chmod -R 777 /tmp/unapproved
COPY file-*.jar /home/app/app.jar
COPY ./src/main/resources/log_properties /home/app
COPY ./src/main/resources/scripts /home/app
RUN chmod +X /home/app/*.sh
ENTRYPOINT ["sh", "/home/app/run.sh"]