FROM alpine/git as download_middleware
LABEL VERSION=0.6.4
ARG BRANCH=master
ARG REPO=https://github.com/halushko/kino-cat.git
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin $REPO && \
    git config core.sparseCheckout true && \
    echo "middleware/" >> .git/info/sparse-checkout && \
    git pull origin $BRANCH

FROM gradle:jdk8-alpine
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app
COPY --chown=gradle:gradle --from=download_middleware /home/git/code /home/gradle/code
RUN cd /home/gradle/code/kino-cat/middleware && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar