FROM openjdk:8-alpine
ARG CONFIG_DIR
VOLUME ["/sys/fs/cgroup"]
RUN apk add transmission-daemon transmission-cli openrc
RUN mkdir -p /home/media/torrent/downloads && \
    mkdir -p /home/media/torrent/complete && \
    mkdir -p /home/media/torrent/torrent_files && \
    chmod 777 -R /home/app && \
    chmod 777 -R /home/media \
RUN openrc
RUN touch /run/openrc/softlevel
COPY *.jar /home/app/torrent.jar
COPY $CONFIG_DIR/config_files/transmission/* /var/lib/transmission/config
#COPY $CONFIG_DIR/commands/transmission/* /home/app
CMD echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service transmission-daemon stop && \
    rc-service transmission-daemon start && \
    java -jar /home/app/torrent.jar