FROM alpine/git as download_image
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin https://github.com/halushko/kino-cat.git && \
    git config core.sparseCheckout true && \
    echo "rabKot/" >> .git/info/sparse-checkout && \
    echo "microBot/" >> .git/info/sparse-checkout && \
    git pull origin master

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app

COPY --chown=gradle:gradle --from=download_image /home/git/code /home/gradle/code

RUN cd /home/gradle/code/kino-cat/rabKot && gradle jar && cp ./build/libs/*.jar /home/gradle/kot_utils.jar
RUN cd /home/gradle/code/kino-cat/microBot && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/micro_bot.jar

FROM openjdk:8-alpine as microBot
COPY --from=build_image /home/gradle/app /home/app
ENTRYPOINT ["java", "-jar", "/home/app/micro_bot.jar"]