FROM alpine/git as download_image
ARG BRANCH=master
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin https://github.com/halushko/kino-cat.git && \
    git config core.sparseCheckout true && \
    echo "middleware/" >> .git/info/sparse-checkout && \
    echo "fileConsumer/" >> .git/info/sparse-checkout && \
    git pull origin $BRANCH

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app

COPY --chown=gradle:gradle --from=download_image /home/git/code /home/gradle/code

RUN cd /home/gradle/code/kino-cat/middleware && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar
RUN cd /home/gradle/code/kino-cat/fileConsumer && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/file_consumer.jar

FROM openjdk:8-alpine as fileConsumer
RUN mkdir -p /home/torrent_files/
#COPY --from=download_image /home/git/code /home/app/code
COPY --from=build_image /home/gradle/app /home/app
ENTRYPOINT ["java", "-jar", "/home/app/file_consumer.jar"]