FROM alpine/git as download_bot
LABEL VERSION=0.6.4
ARG BRANCH=master
ARG REPO=https://github.com/halushko/kino-cat.git
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin $REPO && \
    git config core.sparseCheckout true && \
    echo "bot/" >> .git/info/sparse-checkout && \
    git pull origin $BRANCH

FROM halushko/cinema-middleware:tmp as build_bot
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app
COPY --chown=gradle:gradle --from=download_bot /home/git/code /home/gradle/code
RUN cd /home/gradle/code/kino-cat/bot && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/bot.jar

FROM openjdk:8-alpine as bot
COPY --from=build_bot /home/gradle/app /home/app
ENTRYPOINT ["java", "-jar", "/home/app/bot.jar"]