FROM alpine/git as download_image
LABEL "v 1.0"
RUN mkdir -p /home/git/code
RUN cd /home/git/code && git clone --depth 1 https://github.com/halushko/kino-cat.git && ls
RUN ls /home/git/code/kino-cat

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code/rabKot
RUN mkdir -p /home/gradle/app

COPY --from=download_image /home/git/code/kino-cat/rabKot /home/gradle/code/rabKot

RUN ls /home/gradle/code/rabKot

RUN cd /home/gradle/code/rabKot && \
	gradle jar && \
    cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar

RUN rm -rf /home/gradle/code