FROM alpine/git as download_image
LABEL VERSION=0.5
ARG BRANCH=master
ARG REPO=https://github.com/halushko/kino-cat.git
RUN mkdir -p /home/git/code
RUN cd /home/git/code && \
    git init kino-cat && \
    cd kino-cat && \
    git remote add origin $REPO && \
    git config core.sparseCheckout true && \
    echo "middleware/" >> .git/info/sparse-checkout && \
    echo "minidlna/" >> .git/info/sparse-checkout && \
    echo "config/commands/minidlna/" >> .git/info/sparse-checkout && \
    echo "config/config_files/minidlna/" >> .git/info/sparse-checkout && \
    git pull origin $BRANCH

FROM gradle:jdk8-alpine as build_image
RUN mkdir -p /home/gradle/code
RUN mkdir -p /home/gradle/app

COPY --chown=gradle:gradle --from=download_image /home/git/code /home/gradle/code

RUN cd /home/gradle/code/kino-cat/middleware && gradle jar && cp ./build/libs/*.jar /home/gradle/app/kot_utils.jar
RUN cd /home/gradle/code/kino-cat/minidlna && gradle fatJar && cp ./build/libs/*.jar /home/gradle/app/minidlna.jar

FROM openjdk:8-alpine
RUN apk add openrc
VOLUME ["/sys/fs/cgroup"]
VOLUME ["/var/cache/minidlna"]
VOLUME ["/var/db/minidlna"]
VOLUME ["/var/log/"]
VOLUME ["/home/media"]

ENV PUID=minidlna
ENV PGID=minidlna

COPY --from=build_image /home/gradle/app /home/app

RUN apk add minidlna sqlite
COPY --from=download_image /home/git/code/kino-cat/config/config_files/minidlna /etc
COPY --from=download_image /home/git/code/kino-cat/config/commands/minidlna /home/app

RUN openrc
RUN touch /run/openrc/softlevel
RUN mkdir -p /var/db/minidlna && \
    mkdir -p /var/cache/minidlna && \
    mkdir -p /var/log/ && \
    mkdir -p /home/media && \
    chown minidlna /var/cache/minidlna && \
    chown minidlna /var/db/minidlna && \
    chown minidlna /var/log/ && \
    chown minidlna /home/media && \
    chmod +X /home/app/*.sh

CMD chmod 777 -R /home/app && \
    chmod 777 -R /home/media && \
    chmod 777 -R /var/db/minidlna && \
    chmod 777 -R /var/cache/minidlna && \
    chmod 777 -R /var/log/ && \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service minidlna start && \
    java -jar /home/app/minidlna.jar