FROM openjdk:8-alpine as torrent
VOLUME ["/sys/fs/cgroup"]

RUN apk add openrc

RUN apk add transmission-daemon transmission-cli

COPY ./jars/kot_utils.jar /home/gradle/app /home/app/kot_utils.jar
COPY ./jars/torrent.jar /home/gradle/app /home/app/torrent.jar
COPY ./jars/config/config_files/transmission /var/lib/transmission/config
COPY ./jars/config/commands/transmission /home/app

RUN chmod +x /var/lib/transmission/config/after_download.sh
RUN openrc
RUN touch /run/openrc/softlevel

CMD chmod 777 -R /home/app && \
    chmod +X /home/app/*.sh && \
    cp /home/jars/kot_utils.jar /home/app && \
    cp /home/jars/torrent.jar /home/app && \
    mkdir -p /home/media/torrent/downloads && \
    mkdir -p /home/media/torrent/complete && \
    mkdir -p /home/media/torrent/torrent_files && \
    chown transmission -R /home/media && \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service transmission-daemon stop && \
    rc-service transmission-daemon start && \
    java -jar /home/app/torrent.jar