FROM openjdk:8-alpine as mediaServer
VOLUME ["/sys/fs/cgroup"]
RUN apk add openrc

VOLUME ["/var/cache/minidlna"]
VOLUME ["/var/db/minidlna"]
VOLUME ["/var/log/"]
VOLUME ["/home/media"]

ENV PUID=minidlna
ENV PGID=minidlna

#ENV MINIDLNA_media_dir=V,/media
#ENV MINIDLNA_friendly_name=MiniDLNA
#ENV MINIDLNA_merge_media_dirs=yes
#ENV MINIDLNA_force_sort_criteria="upnp:class, upnp:originalTrackNumber, dc:title"
#ENV MINIDLNA_root_container=B

RUN apk add minidlna

COPY ./jars/kot_utils.jar /home/gradle/app /home/app/kot_utils.jar
COPY ./jars/minidlna.jar /home/gradle/app /home/app/torrent.jar
COPY ./jars/config/config_files/minidlna /etc
COPY ./jars/config/commands/minidlna /home/app

RUN openrc
RUN touch /run/openrc/softlevel
RUN mkdir -p /var/db/minidlna && \
    mkdir -p /home/media

#RUN rc-service minidlna start && \
#    rc-update add minidlna default

#    rc-service minidlna stop && \
#
CMD chmod +X /home/app/*.sh && \
    chmod 777 -R /home/app && \
    cp /home/jars/kot_utils.jar /home/app && \
    cp /home/jars/minidlna.jar /home/app && \
    chmod 777 -R /home/app && \
    chmod 777 -R /home/media && \
    chmod 777 -R /var/db/minidlna && \
    chmod 777 -R /var/cache/minidlna && \
    chmod 777 -R /var/log/ && \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service minidlna start && \
    java -jar /home/app/minidlna.jar