FROM openjdk:8-alpine as fileConsumer
COPY ./jars/kot_utils.jar /home/gradle/app /home/app/kot_utils.jar
COPY ./jars/bot.jar /home/gradle/app /home/app/file_consumer.jar
ENTRYPOINT ["java", "-jar", "/home/app/file_consumer.jar"]