FROM openjdk:8-alpine as mediaServer
VOLUME ["/sys/fs/cgroup"]
VOLUME ["/var/cache/minidlna"]
VOLUME ["/var/db/minidlna"]
VOLUME ["/var/log/"]
VOLUME ["/home/media"]
VOLUME ["/home/app"]

RUN apk add openrc


ENV PUID=minidlna
ENV PGID=minidlna

#ENV MINIDLNA_media_dir=V,/media
#ENV MINIDLNA_friendly_name=MiniDLNA
#ENV MINIDLNA_merge_media_dirs=yes
#ENV MINIDLNA_force_sort_criteria="upnp:class, upnp:originalTrackNumber, dc:title"
#ENV MINIDLNA_root_container=B

RUN apk add minidlna

RUN openrc
RUN touch /run/openrc/softlevel
RUN mkdir -p /var/db/minidlna && \
    mkdir -p /home/media && \
    mkdir -p /home/app

#RUN rc-service minidlna start && \
#    rc-update add minidlna default

#    rc-service minidlna stop && \
#
CMD cp -rf /home/app/config/config_files/minidlna/* /etc/ && \
    cp -rf /home/app/config/commands/minidlna/*.sh /home/app/ && \
    chmod +X /home/app/*.sh && \
    chmod 777 -R /home/app && \
    chmod 777 -R /home/app && \
    chmod 777 -R /home/media && \
    chmod 777 -R /var/db/minidlna && \
    chmod 777 -R /var/cache/minidlna && \
    chmod 777 -R /var/log/ && \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service minidlna start && \
    java -jar /home/app/minidlna.jar