FROM openjdk:8-alpine as textConsumer
VOLUME ["/home/jars"]
VOLUME ["/home/app"]
RUN mkdir -p /home/jars
RUN mkdir -p /home/app
CMD chmod 777 -R /home/app && \
    cp /home/jars/kot_utils.jar /home/app && \
    cp /home/jars/text_consumer.jar /home/app && \
    java -jar /home/app/text_consumer.jar