FROM openjdk:8-alpine as torrent
VOLUME ["/sys/fs/cgroup"]
VOLUME ["/home/app"]

RUN apk add openrc

RUN apk add transmission-daemon transmission-cli

RUN openrc
RUN touch /run/openrc/softlevel

RUN mkdir -p /home/app

CMD cp -rf /home/app/config/config_files/transmission/* /var/lib/transmission/config/ && \
    cp -rf /home/app/config/commands/transmission/*.sh /home/app/ && \
    chmod +x /var/lib/transmission/config/after_download.sh && \
    chmod 777 -R /home/app && \
    chmod +X /home/app/*.sh && \

    mkdir -p /home/media/torrent/downloads && \
    mkdir -p /home/media/torrent/complete && \
    mkdir -p /home/media/torrent/torrent_files && \
    chown transmission -R /home/media && \

    echo 'rc_provide="loopback net"' >> /etc/rc.conf && \
    rc-service transmission-daemon stop && \
    rc-service transmission-daemon start && \
    java -jar /home/app/torrent.jar