package com.halushko.kinocat.core;

@SuppressWarnings("unused")
public interface Queues {
    interface Telegram {
        String TELEGRAM_INPUT_FILE = "TELEGRAM_INPUT_FILE_QUEUE";
        String TELEGRAM_OUTPUT_TEXT = "TELEGRAM_OUTPUT_TEXT_QUEUE";
        String TELEGRAM_INPUT_TEXT = "TELEGRAM_INPUT_TEXT_QUEUE";
    }

    interface Torrent {
        String TORRENTS_LIST = "EXECUTE_TORRENT_COMMAND_LIST";
        String FILES_LIST = "EXECUTE_TORRENT_COMMAND_LIST_FILES";
        String TORRENT_INFO = "EXECUTE_TORRENT_COMMAND_INFO";
        String TORRENT_COMMANDS = "EXECUTE_TORRENT_COMMAND_SHOW_COMMANDS";
        String RESUME_TORRENT = "EXECUTE_TORRENT_COMMAND_RESUME_TORRENT";
        String PAUSE_TORRENT = "EXECUTE_TORRENT_COMMAND_PAUSE_TORRENT";
        String RESUME_ALL = "EXECUTE_TORRENT_COMMAND_RESUME_ALL_TORRENTS";
        String PAUSE_ALL = "EXECUTE_TORRENT_COMMAND_PAUSE_ALL_TORRENTS";
        String DELETE = "EXECUTE_TORRENT_COMMAND_DELETE";
        String DELETE_ONLY_TORRENT = "EXECUTE_TORRENT_COMMAND_DELETE_ONLY_TORRENT";
        String DELETE_WITH_FILES = "EXECUTE_TORRENT_COMMAND_DELETE_WITH_FILES";
        String SEARCH_BY_NAME = "EXECUTE_TORRENT_COMMAND_SEARCH_BY_NAME";
        String LIST_TORRENTS_IN_DOWNLOAD_STATUS = "EXECUTE_LIST_TORRENTS_IN_DOWNLOAD_STATUS";
    }

    interface Text {
        String HELP = "DISPLAY_ALL_COMMANDS";
    }

    interface File {
        String CHOOSE_THE_DESTINATION = "FILE_CHOOSE_THE_DESTINATION";
        String MOVE_TO_FOLDER = "FILE_MOVE_TO_FOLDER";
    }
}
